//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounting
    {
        public long id { get; set; }
        public System.DateTime startWork { get; set; }
        public Nullable<System.DateTime> endwork { get; set; }
        public long user { get; set; }
        public long status { get; set; }
    
        public virtual status status1 { get; set; }
        public virtual user user1 { get; set; }
    }
}
